name: ci

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        architecture: [amd64, arm64]
        runner_os:
          - ${{ 'ubuntu-24.04' if eq(matrix.architecture, 'amd64') }}
          - ${{ 'ubuntu-24.04-arm64' if eq(matrix.architecture, 'arm64') }}
    runs-on: ${{ matrix.runner_os }}
    name: build-${{ matrix.architecture }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Show environment
        run: make show-env
      - name: Build watchmaker
        run: make build_native
      - name: Build examples
        run: make examples
