name: ci

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Show environment
        run: make show-env
      - name: Build watchmaker
        run: make build_amd64
      - name: Build examples
        run: make examples
